# -*- coding: utf-8 -*-
"""ein990pdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18FUCCe0uRdFyIZzr2wXEsQQMDkuKzOfr
"""

import requests
import tkinter as tk
from bs4 import BeautifulSoup

def download_pdf(pdf_url):
    response = requests.get(pdf_url)
    if response.status_code == 200:
        pdf_filename = pdf_url.split("/")[-1]
        with open(pdf_filename, 'wb') as pdf_file:
            pdf_file.write(response.content)
            status_label.config(text=f"Downloaded {pdf_filename}")
    else:
        status_label.config(text=f"Failed to download {pdf_url}")

def download_pdfs():
    ein_list = ein_entry.get().split()
    base_url = "https://apps.irs.gov/pub/epostcard/cor/"
    for ein in ein_list:
        ein_url = f"{base_url}{ein}.pdf"
        download_pdf(ein_url)

app = tk.Tk()
app.title("EIN PDF Downloader")

instruction_label = tk.Label(app, text="Enter EINs separated by spaces or carriage returns:")
instruction_label.pack()

ein_entry = tk.Entry(app)
ein_entry.pack()

download_button = tk.Button(app, text="Download PDFs", command=download_pdfs)
download_button.pack()

status_label = tk.Label(app, text="")
status_label.pack()

app.mainloop()